name: sudoku_solver_model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          ## pip install -r requirements.txt
          ## python sudoku_solver01.py
          
          # result accuracy:
          ## echo "result accuracy on test: "
          ## cat results.txt
          # Write your CML report
          # cat results.txt >> report.md
          # cml-send-comment report.md
